### ISSUE TITLE
Suggestion: permission problem

### ISSUE THREAD

**Issue by mason1900** [PrivateBin/docker-nginx-fpm-alpine#10] opened 2019-10-26 04:08 UTC
Related issue: #2 

Probably you can add something like this in the `Dockerfile`:
```
ARG UID=65534
ARG GID=82
usermod -u $UID nobody
groupmod -g $GID www-data
```
And add the following instruction to the `README.md` : `chown -R 65534:82 data/`

**Comment by elrido** [comment] 2019-10-26 16:19
The alpine image this is based on has that user already created in its /etc/passwd and the group is created by the nginx package installation, so there is no need to created these explicitly in the Dockerfile. You can confirm this yourself by running:
```shell
$ docker run -ti --rm --entrypoint /bin/ash privatebin/nginx-fpm-alpine
/var/www $ grep nobody /etc/passwd
nobody:x:65534:65534:nobody:/:/sbin/nologin
/var/www $ grep www-data /etc/group
www-data:x:82:nginx
/var/www $ exit
```

**Comment by mason1900** [comment] 2019-10-26 19:28
`GID 82` is not obvious before the alpine container is build, and it might change with alpine image or nginx in the future. Adding an `ARG` allow image builder to control the UID and GID before the image is built.

**Comment by elrido** [comment] 2019-10-28 05:45
65534 is very unlikely to change, as that is AFAIK part of the POSIX standard for the nobody user. The GID 82 seems to be a quasi standard on Debian and Alpine, but could change if switching to another distro. At that time we would definitely have to check if the image still works with the same permissions as before and add missing groups, if necessary, so an upgrade of the image wouldn't require permission changes.

**Comment by mason1900** [comment] 2019-10-30 20:33
> The GID 82 seems to be a quasi standard on Debian and Alpine

No, that's no true. On Debian 9.9+ (I have not tested versions below 9.9) the default GID for `www-data` is `33`. On Ubuntu it is also 33.
I encountered the permission problem myself before I noticed the instructions about setting the owner to `65534:82`.

**Comment by elrido** [comment] 2019-10-31 12:58
The host doesn't matter for this: Only the /etc/groups file _inside_ of the image is consulted when resolving the name `www-data` by nginx or php-fpm for the appropriate GID.

Of course outside of the container, on your host, that ID might match to something else, which is why outside of the container you may have to use a numeric user and group ID to fix the permissions. This is not in the scope of the Dockerfile and it is documented:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/d393fc5c89e225560e6bf0df23a227b8fc842f3f/README.md#L23

**Comment by mason1900** [comment] 2019-11-03 07:10
> Only the /etc/groups file _inside_ of the image is consulted when resolving the name `www-data` by nginx or php-fpm for the appropriate GID.

I know this already. It's my mistake that I did not carefully read through the instructions.

However, I am just saying that those lines that I provided above explicitly set the GID of `www-data`, so that in case the upstream make any unexpected changes, the number is always fixed to `82`.

Besides, those lines give the users of the docker image an option to set the GID with `--build-arg GID=XXX` during build time without forcing them to modify the Dockerfile or chown anything (for a bind mount setting). 

Also I don't think they will break anything, as the numbers are unchanged as for now.

**Comment by TheBigK02** [comment] 2021-04-27 09:55
I agree what mason is saying. The problem is outside the docker scope I might have matching groups which i dont want. I want those ids to be unique in my environment to not have problems with one application can delete the files of another. its unlike since those are mounts but also not impossible. Thats why using arugments for userid and gid is a nice way to adjust the behavior to your needs.

I would rly appreciate changes made to the image.

**Closed** 2021-04-28 16:30 UTC

**Comment by elrido** [comment] 2021-04-28 16:45
Ok, I had been under the mistaken impression that the image is already able to run as any user id. Some quick tests proved that was not the case.

I have now done some changes that will let us run the image with any non-root user id. For example, with docker:
```
mkdir data
docker run -d --rm --read-only -p 8080:8080 -v $PWD/data:/srv/data --user $(id -u):$(id -g) --name pb privatebin/nginx-fpm-alpine
docker logs pb
[28-Apr-2021 16:22:03] NOTICE: fpm is running, pid 38
[28-Apr-2021 16:22:03] NOTICE: ready to handle connections
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
firefox http://localhost:8080/
[create a paste]
ls -ln data
total 16
drwx------ 3 1000 1000 4096 Apr 28 18:23 09
-rw-r----- 1 1000 1000   45 Apr 28 18:23 purge_limiter.php
-rw-r----- 1 1000 1000  522 Apr 28 18:23 salt.php
-rw-r----- 1 1000 1000  130 Apr 28 18:23 traffic_limiter.php
docker stop pb
```

For k8s, the example deployment from the README.md could be adjusted like so, to run as UID 1234 / GID 5678:
```
      initContainers:
      - name: privatebin-volume-permissions
        image: privatebin/chown:1.33.0-musl-1.2.2-r0
        args: ['1234:5678', '/mnt']
[...]
      containers:
      - name: privatebin
[...]
        securityContext:
          runAsUser: 1234
          runAsGroup: 5678
```

It is unfortunate that docker and k8s still don't support per-container [user namespace remapping](https://kinvolk.io/blog/2020/12/improving-kubernetes-and-container-security-with-user-namespaces/), which LXC/LXD containers do [since 2015](https://blog.benoitblanchon.fr/lxc-unprivileged-container/). With that a user ID in one container would never be the same as those in another or on the host itself.
